apiVersion: v1
kind: Namespace
metadata:
  name: strimzi-kafka

---
apiVersion: v1
kind: Namespace
metadata:
  name: icoe-kafka

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: strimzi
  namespace: flux-system
spec:
  interval: 10m
  url: https://strimzi.io/charts/

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: strimzi-kafka-operator
  namespace: icoe-kafka
spec:
  interval: 5m
  releaseName: strimzi-kafka-operator
  targetNamespace: icoe-kafka
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: 0.42.0
      sourceRef:
        kind: HelmRepository
        name: strimzi
        namespace: flux-system
  values:
    watchNamespaces: ["icoe-kafka"]
